steps:
- name: 'vizzu/vizzu-devenv'
  args: [ 'mkdir', '-p', '/workspace/build/cmake-desktop' ]
  waitFor: ['-']
  id: 'create_build_folder-desktop'
- name: 'vizzu/vizzu-devenv'
  args: [ 'cmake', '../../project/cmake/' ]
  dir: '/workspace/build/cmake-desktop'
  waitFor: ['create_build_folder-desktop']
  id: 'cmake-desktop'
- name: 'vizzu/vizzu-devenv'
  args: [ 'make' ]
  dir: '/workspace/build/cmake-desktop'
  timeout: 1800s
  waitFor: ['cmake-desktop']
  id: 'make-desktop'
- name: 'vizzu/vizzu-devenv-wasm'
  args: [ 'mkdir', '-p', '/workspace/build/cmake-wasm' ]
  waitFor: ['-']
  id: 'create_build_folder-wasm'
- name: 'vizzu/vizzu-devenv-wasm'
  args: [ '/root/emsdk/upstream/emscripten/emcmake', 'cmake', '../../project/cmake/' ]
  dir: '/workspace/build/cmake-wasm'
  waitFor: ['create_build_folder-wasm']
  id: 'cmake-wasm'
- name: 'vizzu/vizzu-devenv-wasm'
  args: [ 'make' ]
  dir: '/workspace/build/cmake-wasm'
  timeout: 1800s
  waitFor: ['cmake-wasm']
  id: 'make-wasm'
options:
 machineType: 'E2_HIGHCPU_8'
timeout: 1800s
